# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
