# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20170611_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpod',
            name='player_count',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='draftpod',
            name='draft_date',
            field=models.DateTimeField(),
        ),
    ]
